inputType: HIPCHAT
timeZone: America/New_York
computeConfig:
    apiDateFormat: YYYY-MM-dd
    classifier: compute/classifiers/english.all.3class.distsim.crf.ser.gz
    filesToRead:
        'com.chatalytics.bolts.sentiment.words': files/sentiment_words.csv
    chatConfig: !!com.chatalytics.core.config.HipChatConfig
        baseAPIURL: https://api.hipchat.com/v1/
        authTokens: ['0']
webConfig:
    port: 8080
